# configs/puoberta.yaml
model_name: dsfsi/PuoBERTa
max_length: 128
lr: 1e-5
weight_decay: 0.01
epochs_cv: 5
epochs_final: 10
batch_train: 16
batch_eval: 64
class_weights: [1.0, 2.0]
seeds: [42, 0, 13]

